### ISSUE TITLE
Create tests for Categories

### ISSUE THREAD

**Issue by RafaR01** [ci2-ipt/SearchEngine_SIGQ#14]
### What is the objective of this issue?
Create a couple of usefull tests to help identify possible errors related to the Category model.

---
### Do you have any idea how this could be done, or what could happen?
At the category_test.rb file can be created some assert tests.

---

**Comment by renatopanda** [comment]
@RafaR01 sugestão: já que estás a começar com os testes (e espero que a acabar também), para ficar bonito devem configurar uma Action para testar o código + análise estática + linter nos pushes / pull requests para o main.

Ver este vídeo e seguir caso não tenham apanhado a lógica na aula sobre testes, não esquecer que depois pode ser necessário explicar à equipa/turma: https://www.youtube.com/watch?v=iztoY4DnSkw
