### ISSUE TITLE
Visual Part for Login and Register

### ISSUE THREAD

**Issue by t0t0cas** [ci2-ipt/SearchEngine_SIGQ#24]
### What is the objective of this issue?
Making some css using bootstrap for login and register.
---
### Do you have any idea how this could be done, or what could happen?
Using bootstrap 

---

**Comment by renatopanda** [comment]
Info útil, as views por defeito não aparecem, é preciso gerar as mesmas se as quiserem customizar: https://github.com/heartcombo/devise#configuring-views (se não tiver sido feito já pelo @RafaR01).
