### ISSUE TITLE
Initial steps into OAuth

### ISSUE THREAD

**Issue by Sousa1909** [ci2-ipt/SearchEngine_SIGQ#6]
### What is the objective of this issue?
Research and an attempt to add Azure Auth to the project.

---
### Do you have any idea how this could be done, or what could happen?
Here are some links:
* Devise + Rails7:  https://www.digitalocean.com/community/tutorials/how-to-set-up-user-authentication-with-devise-in-a-rails-7-application
* Devise + Rails 6 + Azure AD (Note that this is for Rails 6):  https://medium.com/committed-engineers/setup-azure-ad-oauth-2-0-with-ruby-on-rails-and-devise-39848e3ed532
* Different gem: https://devot.team/blog/how-to-implement-sign-in-with-microsoft-using-the-office-365-omniauth-strategy-with-rails-7

---
### Additional context
![star-wars-dark-side](https://user-images.githubusercontent.com/80701707/207165790-bad2f24c-7c15-446d-b509-e8824d37fa5c.gif)

**Comment by renatopanda** [comment]
@RafaR01 será só isto? https://github.com/heartcombo/devise/wiki/Troubleshooting-Rails-7-and-Turbo-Drive

**Comment by RafaR01** [comment]
@renatopanda não, tentei agora mas continuo a ter a mesma mensagem sempre que inicio o servidor, os redirecionamentos funcionam e tudo mais, mas dá sempre esse erro.

**Comment by RafaR01** [comment]
![image](https://user-images.githubusercontent.com/80701627/212890945-77f5965f-f64e-495b-a28b-ca7a0ea5dea2.png)
